CREATE TABLE `microsoft_account` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `username` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '用户名',
  `password` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '密码',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `last_score` bigint DEFAULT NULL,
  `latest_score` bigint DEFAULT NULL,
  `status` int DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (1, 'kevinyulk@163.com', 'zhujing520', NOW(), NOW(), 4127, 4127, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (2, 'hangzhouhuawei@hotmail.com', 'yupaopao990', NOW(), NOW(), 1335, 1335, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (3, 'hangzhouhuawei1@outlook.com', 'yupaopao990', NOW(), NOW(), 866, 866, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (4, 'hangzhouhuawei2@outlook.com', 'yupaopao990', NOW(), NOW(), 632, 632, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (5, 'hangzhouhuawei3@outlook.com', 'yupaopao990', NOW(), NOW(), 427, 427, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (6, 'shaoyifu1@outlook.com', 'yupaopao990', NOW(), NOW(), 484, 484, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (7, 'shaoyifu2@outlook.com', 'yupaopao990', NOW(), NOW(), 450, 450, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (8, 'shaoyifu3@outlook.com', 'yupaopao990', NOW(), NOW(), 451, 451, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (9, 'yangguangcheng11@outlook.com', 'yupaopao990', NOW(), NOW(), 423, 423, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (10, 'fuyangnongshang1@outlook.com', 'yupaopao990', NOW(), NOW(), 442, 442, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (11, 'fuyangdongqiao@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (12, 'jingdongwuxianbao@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (13, 'hangzhouhaikang@outlook.com', 'yupaopao990', NOW(), NOW(), 264, 264, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (14, 'yulingkai110@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (15, 'yulingkai111@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (16, 'yulingkai120@outlook.com', 'yupaopao990', NOW(), NOW(), 234, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (17, 'yulingkai122@hotmail.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (18, 'yulingkai123@hotmail.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (19, 'zhujing119@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (20, 'yuyouming110@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (21, 'yulingkai220@outlook.com', 'yupaopao990', NOW(), NOW(), 201, NULL, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (22, 'yulingkai221@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (23, 'yulingkai2021@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (24, 'yulingkai2022@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (25, 'yulingkai2023@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (26, 'yulingkai2024@outlook.com', 'yupaopao990', NOW(), NOW(), 204, NULL, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (27, 'yulingkai2025@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (28, 'yulingkai2026@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (29, 'yulingkai2027@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (30, 'yulingkai2028@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (31, 'yulingkai2029@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (32, 'yulingkai2030@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (33, 'yulingkai2031@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (34, 'yulingkai2032@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (35, 'yulingkai2033@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (36, 'yulingkai2034@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (37, 'yulingkai2035@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (38, 'yulingkai2036@outlook.com', 'yupaopao990', NOW(), NOW(), 165, NULL, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (39, 'yulingkai2037@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (40, 'yulingkai2038@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (41, 'yulingkai2039@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (42, 'yulingkai2040@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (43, 'yulingkai2041@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (44, 'yulingkai2042@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (45, 'yulingkai2043@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (46, 'yulingkai2044@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (47, 'yulingkai2045@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (48, 'yulingkai2046@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (49, 'yulingkai2047@outlook.com', 'yupaopao990', NOW(), NOW(), 87, NULL, 1);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (50, 'yulingkai2048@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (51, 'yulingkai2049@outlook.com', 'yupaopao990', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (52, 'yulingkai2050@outlook.com', 'yupaopao990', NOW(), NOW(), 200, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (53, 'yulingkai2051@outlook.com', 'yupaopao990', NOW(), NOW(), 200, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (54, 'yulingkai2052@outlook.com', 'yupaopao990', NOW(), NOW(), 200, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (55, 'yulingkai2053@outlook.com', 'yupaopao990', NOW(), NOW(), 200, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (56, 'yupaopao2054@outlook.com', 'yupaopao990', NOW(), NOW(), 200, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (57, 'yupaopao2055@outlook.com', 'yupaopao990', NOW(), NOW(), 200, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (58, 'yupaopao2056@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (59, 'yupaopao2057@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (60, 'yupaopao2058@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (61, 'yupaopao2059@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (62, 'yulingkai2060@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (63, 'yulingkai2061@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (64, 'yulingkai2062@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (65, 'yulingkai2063@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);
INSERT INTO `microsoftrewards`.`microsoft_account` (`id`, `username`, `password`, `update_time`, `create_time`, `last_score`, `latest_score`, `status`) VALUES (66, 'yulingkai2064@outlook.com', 'yupaopao990', NOW(), NOW(), 700, NULL, 0);